accounts/urls.py
from django.urls import path

from .views import SignUpView, UserEditView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("edit/", UserEditView.as_view(), name="user_edit"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("todo.urls")),
]

todo/urls.py
from django.urls import path
from .views import (
    HomePageView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskDeleteView,
    TaskUpdateView,
    NoteEditView,
    NoteDeleteView,
)

urlpatterns = [
    path("notes/<int:pk>/edit/", NoteEditView.as_view(), name="note_edit"),
    path("notes/<int:pk>/delete/", NoteDeleteView.as_view(), name="note_delete"),
    path("tasks/add/", TaskCreateView.as_view(), name="task_add"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("", HomePageView.as_view(), name="home"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)
    GENDER_CHOICES = (
        ("male", "Male"),
        ("female", "Female"),
        ("none", "None"),
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="none")
    date_of_birth = models.DateField(_("birthday"), null=True)
    REQUIRED_FIELDS = [
        "first_name",
        "last_name",
        "email",
        "date_of_birth",
    ]

    def __str__(self):
        return self.username

todo/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    STATUS_CHOICES = (
        ("todo", "Todo"),
        ("doing", "Doing"),
        ("done", "Done"),
    )
    status = models.CharField(max_length=5, choices=STATUS_CHOICES)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy("task_detail", kwargs={"pk": self.pk})


class Note(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    note = models.CharField(max_length=200)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "gender",
            "email",
            "date_of_birth",
        )
        widgets = {"date_of_birth": forms.widgets.DateInput(attrs={"type": "date"})}


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields


class UserEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "gender",
            "email",
            "date_of_birth",
        )
        widgets = {"date_of_birth": forms.widgets.DateInput(attrs={"type": "date"})}

todo/forms.py
from django import forms
from .models import Task, Note


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "status",
            "due_date",
        ]
        widgets = {
            "due_date": forms.widgets.DateTimeInput(attrs={"type": "datetime-local"}),
        }


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = [
            "note",
        ]

accounts/views.py
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm, UserEditForm
from .models import CustomUser


# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    model = CustomUser
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class UserEditView(UpdateView):
    model = CustomUser
    form_class = UserEditForm
    template_name = "registration/user_edit.html"
    success_url = reverse_lazy("home")

    def get_object(self, queryset=None):
        pk = self.request.user.pk
        return self.model.objects.get(pk=pk)

todo/views.py
from django.http import HttpRequest, HttpResponse
from django.views import View
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    FormView,
)
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from .forms import TaskForm, NoteForm
from .models import Task, Note


# Create your views here.
class HomePageView(TemplateView):
    template_name = "home.html"


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task_list.html"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)


class NoteGet(UserPassesTestMixin, DetailView):
    model = Task
    template_name = "task_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = NoteForm
        return context

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class NotePost(SingleObjectMixin, FormView):
    model = Task
    form_class = NoteForm
    template_name = "task_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        note = form.save(commit=False)
        note.task = self.object
        note.save()
        return super().form_valid(form)

    def get_success_url(self):
        task = self.object
        return reverse("task_detail", kwargs={"pk": task.pk})


class TaskDetailView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = NoteGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = NotePost.as_view()
        return view(request, *args, **kwargs)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = "task_add.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = reverse_lazy("task_list")

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "task_edit.html"

    def test_func(self):
        object = self.get_object()
        return object.user == self.request.user


class NoteEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Note
    fields = ["note"]
    template_name = "note_edit.html"

    def get_success_url(self):
        return reverse("task_detail", kwargs={"pk": self.object.task.pk})

    def test_func(self):
        object = self.get_object()
        return object.task.user == self.request.user


class NoteDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Note
    template_name = "note_delete.html"

    def get_success_url(self):
        return reverse("task_detail", kwargs={"pk": self.object.task.pk})

    def test_func(self):
        object = self.get_object()
        return object.task.user == self.request.user

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
        {% block title %}Todo App{% endblock title %}
        </title>
        <h1>Todo App</h1>
        {% if user.is_authenticated %}
            <p><a href="{% url 'home' %}">Home</a> | <a href="{% url 'task_list' %}">Tasks</a> | <a href="{% url 'task_add' %}">+Task</a></p>
        {% else %}
            <p><a href="{% url 'login' %}">Log In</a> | <a href="{% url 'signup' %}">Sign Up</a></p> 
        {% endif %}
        <hr>
        <hr>
    </head>
    <body>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <h4>Hi {{ user.username }}!</h4>
    <p><a href="{% url 'task_list' %}">Task List</a></p>
    <p><a href="{% url 'task_add' %}">Add New Task</a></p>
    <p><a href="{% url 'user_edit' %}">Edit Account</a></p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
    <hr>
{% else %}
    <h4>You are not logged in!</h4>
    <hr>
{% endif %}
{% endblock content %}

templates/note_delete.html
{% extends "base.html" %}

{% block title %}Delete Note{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Do you confirm to delete : {{ note.note }}</p>
    {{ form.as_p }}
    <button type="submit">Delete</button>
    <a href="{% url 'task_detail' note.task.pk %}">Cancel</a>
</form>
{% endblock content %}

templates/note_edit.html
{% extends "base.html" %}

{% block title %}Edit Note{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
    <a href="{% url 'task_detail' note.task.pk %}">Cancel</a>
</form>
{% endblock content %}

templates/task_add.html
{% extends "base.html" %}

{% block title %}Add New Task{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
    <a href="{% url 'home' %}">Cancel</a>
</form>
{% endblock content %}

templates/task_delete.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Do you confirm to delete {{ task.title }}</p>
    {{ form.as_p }}
    <button type="submit">Delete</button>
    <a href="{% url 'task_detail' task.pk %}">Cancel</a>
</form>
{% endblock content %}

templates/task_detail.html
{% extends "base.html" %}

{% block title %}{{ task.title }}{% endblock title %}
{% block content %}
<h4><a href="{% url 'task_list' %}">Back to task list</a> | 
    <a href="{% url 'task_edit' task.pk %}">Edit Task</a> |
    <a href="{% url 'task_delete' task.pk %}">Delete Task</a></h4>
<hr>
<h2>{{ task.title }}</h2>
<p>status : {{ task.status }} 
    {% if task.due_date %}| due_date : {{ task.due_date }}{% endif %}</p>
<h3>Description : </h3>
<p>{{ task.description }}</p>
<hr>
<h2>Notes : </h2>
{% for note in task.note_set.all %}
    <p>{{ note.note }} | 
        <a href="{% url 'note_edit' note.pk %}">Edit</a> | 
        <a href="{% url 'note_delete' note.pk%}">Delete</a></p>
{% endfor %}
<h4>Add Note : </h4>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Note</button>
</form>
<hr>
{% endblock content %}

templates/task_edit.html
{% extends "base.html" %}

{% block title %}Edit Task{% endblock title %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit</button>
    <a href="{% url 'task_detail' task.pk %}">Cancel</a>
</form>
{% endblock content %}

templates/task_list.html
{% extends "base.html" %}

{% block title %}Tasks List{% endblock title %}
{% block content %}
{% for task in task_list %}
    <h3><a href="{% url 'task_detail' task.pk %}">{{ task.title }}</a></h3>
    <p>status : {{ task.status }} 
        {% if task.due_date %}| due_date : {{ task.due_date }}{% endif %}</p>
    <hr>
{% endfor %}
{% endblock content %}